# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRsdt <- function(pairwise, group, weight, tol) {
    .Call('_gpct_getRsdt', PACKAGE = 'gpct', pairwise, group, weight, tol)
}

get_nullSE <- function(winProb_X, winProb_Y, weight_X, weight_Y) {
    .Call('_gpct_get_nullSE', PACKAGE = 'gpct', winProb_X, winProb_Y, weight_X, weight_Y)
}

get_Rcc <- function(pairwise, group, weight, tol) {
    .Call('_gpct_get_Rcc', PACKAGE = 'gpct', pairwise, group, weight, tol)
}

get_pw_numeric <- function(outcome, discriminant) {
    .Call('_gpct_get_pw_numeric', PACKAGE = 'gpct', outcome, discriminant)
}

get_pw_surv <- function(outcome_exists, outcome, direction, censored_as_tie, minDiff) {
    .Call('_gpct_get_pw_surv', PACKAGE = 'gpct', outcome_exists, outcome, direction, censored_as_tie, minDiff)
}

countInconsistency <- function(x, weights, includeTies, m) {
    .Call('_gpct_countInconsistency', PACKAGE = 'gpct', x, weights, includeTies, m)
}

